services:
#    users.example:
#        class: UsersBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]    
    app.form.registration:
        class: UsersBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_users_registration }
